<a href="https://colab.research.google.com/github/shanami/DSCI-261-eng/blob/main/tackling_missing_data_imputing_statistics_missing_indicators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# fillna()

In [ ]:
import pandas as pd
wdi = pd.read_pickle('wdi.pkl')

# Get the names of the numeric columns and the non-numeric columns
numeric_cols = wdi.select_dtypes(include='number').columns
cat_cols = wdi.select_dtypes(exclude='number').columns

In [ ]:
# Returns a Series: each column contains one value, with the index being the column name
# Mean and median both ignore NaN when calculating
wdi[numeric_cols].mean()

access_to_electricity_pct         8.421552e+01
atms_per_100000                   4.812857e+01
compulsory_education_years        9.701456e+00
health_expenditure_pct_of_gdp     6.433350e+00
gdp_per_capita_usd                1.359989e+04
gdp_per_capita_ppp                1.992523e+04
life_expectancy_female            7.456947e+01
life_expectancy_male              6.986652e+01
life_expectancy                   7.217627e+01
population_density                2.099738e+02
population                        3.690135e+08
alcohol_consumption_per_capita    6.016516e+00
unemployment_rate_female          8.404762e+00
unemployment_rate_male            6.465617e+00
unemployment_rate                 7.047682e+00
year                              2.017500e+03
is_region                         2.119816e-01
dtype: float64

In [ ]:
wdi[numeric_cols].median()

access_to_electricity_pct         9.891294e+01
atms_per_100000                   3.941107e+01
compulsory_education_years        1.000000e+01
health_expenditure_pct_of_gdp     6.006967e+00
gdp_per_capita_usd                5.783711e+03
gdp_per_capita_ppp                1.310845e+04
life_expectancy_female            7.608850e+01
life_expectancy_male              7.081350e+01
life_expectancy                   7.358550e+01
population_density                6.961068e+01
population                        1.604842e+07
alcohol_consumption_per_capita    5.837431e+00
unemployment_rate_female          5.836087e+00
unemployment_rate_male            5.351708e+00
unemployment_rate                 5.606500e+00
year                              2.017500e+03
is_region                         0.000000e+00
dtype: float64

In [ ]:
# fillna takes a Series as the fill value: pandas match by column name, so the NaN of each column is replaced by the average of that column
# This command only returns a new table to view, wdi remains unchanged
wdi[numeric_cols].fillna(wdi[numeric_cols].mean())

,access_to_electricity_pct,atms_per_100000,compulsory_education_years,health_expenditure_pct_of_gdp,gdp_per_capita_usd,gdp_per_capita_ppp,life_expectancy_female,life_expectancy_male,life_expectancy,population_density,population,alcohol_consumption_per_capita,unemployment_rate_female,unemployment_rate_male,unemployment_rate,year,is_region
0,97.700000,1.213235,9.0,11.777236,519.884773,2058.383832,65.656000,62.701000,64.130000,55.595993,3.629640e+07,6.016516,14.090000,10.416000,11.184000,2017,0
1,100.000000,31.714076,9.0,5.010597,4531.020806,13037.010016,80.148000,76.601000,78.333000,104.870693,2.873457e+06,6.016516,12.563000,14.590000,13.750000,2017,0
2,100.000000,9.130677,10.0,6.380329,4111.294110,11737.409353,77.735000,75.307000,76.499000,17.377715,4.138920e+07,6.016516,21.114000,10.021000,11.996000,2017,0
3,41.962894,19.079250,6.0,2.791503,4095.812942,7310.901738,63.252000,57.677000,60.379000,23.916538,2.981675e+07,6.016516,7.467000,6.769000,7.119000,2017,0
4,90.283638,27.360620,9.0,5.561266,6108.588220,14562.367966,73.493366,69.921250,71.622526,36.669804,4.118990e+08,6.016516,20.361396,8.097088,10.641313,2017,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,100.000000,25.322499,10.0,5.917897,2566.596950,7771.189420,79.442000,71.207000,75.317000,308.125246,9.554040e+07,8.660000,1.831000,2.142000,1.993000,2018,0
430,100.000000,24.735190,10.0,6.433350,3562.330943,6472.121785,75.595000,72.263000,73.895000,758.984551,4.569087e+06,6.016516,41.849998,22.393999,26.256001,2018,0
431,89.588551,40.949620,10.0,9.848779,11385.675227,17025.827360,74.871815,70.398743,72.563282,59.617978,7.591945e+09,6.181240,5.580954,5.271615,5.392213,2018,1
432,39.812622,11.554664,7.0,4.934843,1516.390661,3607.304442,66.447000,60.533000,63.510000,23.341479,1.735182e+07,6.540000,12.448000,10.614000,11.500000,2018,0
433,41.041584,6.625208,7.0,4.734331,1683.740577,3206.277079,62.598000,59.501000,61.195000,37.324591,1.443902e+07,4.670000,5.598000,4.555000,5.087000,2018,0

In [ ]:
# Similar to the above but assigned to wdi, so the change is real
# This is how pure pandas are equivalent to SimpleImputer(strategy='mean')
wdi[numeric_cols] = wdi[numeric_cols].fillna(wdi[numeric_cols].mean())

In [ ]:
# Count the values, including NaN
# After the cell above, this column no longer has NaN, and the cells that were missing hours all have the same value (which is the average), so that value will appear unusually many times
# This is a familiar consequence of filling in the average: narrowing the distribution
wdi['alcohol_consumption_per_capita'].value_counts(dropna=False)

6.016516     219
0.690000       3
2.050000       2
0.019000       2
9.230000       2
            ...
2.300000       1
8.940000       1
4.065725       1
11.350000      1
2.710000       1
Name: alcohol_consumption_per_capita, Length: 205, dtype: int64

In [ ]:
# For a text column, `describe()` returns 4 rows: count (number of cells that are not missing), unique (number of different values), top (most frequent value, i.e., mode), freq (number of times top appears)
wdi[cat_cols].describe()

       country_name country_category
count           434              282
unique          217                2
top         Belgium       DEVELOPING
freq              2              224

In [ ]:
# .loc['top'] selects the correct top row, outputs Series: index is the column name, value is the most frequent value
wdi[cat_cols].describe().loc['top']

country_name           Belgium
country_category    DEVELOPING
Name: top, dtype: object

In [ ]:
# Save it to the variable most_freq
most_freq = wdi[cat_cols].describe().loc['top']

In [ ]:
# Similar to step 4 but for text columns: each column is filled with its own mode, then written back to wdi
# The last line only displays the result
# This is equivalent to SimpleImputer(strategy='most_frequent')
wdi[cat_cols] = wdi[cat_cols].fillna(most_freq)
wdi[cat_cols]

           country_name country_category
0           Afghanistan       DEVELOPING
1               Albania       DEVELOPING
2               Algeria       DEVELOPING
3                Angola       DEVELOPING
4            Arab World       DEVELOPING
..                  ...              ...
429             Vietnam       DEVELOPING
430  West Bank and Gaza       DEVELOPING
431               World       DEVELOPING
432              Zambia       DEVELOPING
433            Zimbabwe       DEVELOPING

[434 rows x 2 columns]

In [ ]:
wdi['country_category'].value_counts(dropna=False)

DEVELOPING    376
DEVELOPED      58
Name: country_category, dtype: int64

In [ ]:
wdi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country_name                    434 non-null    object
 1   access_to_electricity_pct       434 non-null    float64
 2   atms_per_100000                 434 non-null    float64
 3   compulsory_education_years      434 non-null    float64
 4   health_expenditure_pct_of_gdp   434 non-null    float64
 5   gdp_per_capita_usd              434 non-null    float64
 6   gdp_per_capita_ppp              434 non-null    float64
 7   life_expectancy_female          434 non-null    float64
 8   life_expectancy_male            434 non-null    float64
 9   life_expectancy                 434 non-null    float64
 10  population_density              434 non-null    float64
 11  population                      434 non-null    float64
 12  alcohol_consumption_per_capita  434 non-null    float64
 13  unemployment_rate_female        434 non-null    float64
 14  unemployment_rate_male          434 non-null    float64
 15  unemployment_rate               434 non-null    float64
 16  year                            434 non-null    int64
 17  country_category                434 non-null    object
 18  is_region                       434 non-null    int64
dtypes: float64(15), int64(2), object(2)
memory usage: 64.5+ KB

# SimpleImputer

In [ ]:
wdi = pd.read_pickle('wdi.pkl')
numeric_cols = wdi.select_dtypes(include='number').columns
cat_cols = wdi.select_dtypes(exclude='number').columns

In [ ]:
from sklearn.impute import SimpleImputer
simple_imp_mean = SimpleImputer(strategy='mean')

In [ ]:
imputed_num = simple_imp_mean.fit_transform(wdi[numeric_cols])

In [ ]:
print(imputed_num.shape)
print(wdi[numeric_cols].shape)

(434, 17)
(434, 17)

In [ ]:
wdi[numeric_cols] = imputed_num

In [ ]:
wdi['compulsory_education_years'].value_counts(dropna=False)

9.000000     102
10.000000    100
6.000000      36
12.000000     34
11.000000     31
8.000000      24
9.701456      22
7.000000      20
13.000000     17
14.000000     16
15.000000     10
5.000000       6
9.500000       6
8.500000       4
16.000000      2
6.500000       2
10.500000      2
Name: compulsory_education_years, dtype: int64

In [ ]:
wdi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country_name                    434 non-null    object
 1   access_to_electricity_pct       434 non-null    float64
 2   atms_per_100000                 434 non-null    float64
 3   compulsory_education_years      434 non-null    float64
 4   health_expenditure_pct_of_gdp   434 non-null    float64
 5   gdp_per_capita_usd              434 non-null    float64
 6   gdp_per_capita_ppp              434 non-null    float64
 7   life_expectancy_female          434 non-null    float64
 8   life_expectancy_male            434 non-null    float64
 9   life_expectancy                 434 non-null    float64
 10  population_density              434 non-null    float64
 11  population                      434 non-null    float64
 12  alcohol_consumption_per_capita  434 non-null    float64
 13  unemployment_rate_female        434 non-null    float64
 14  unemployment_rate_male          434 non-null    float64
 15  unemployment_rate               434 non-null    float64
 16  year                            434 non-null    float64
 17  country_category                282 non-null    object
 18  is_region                       434 non-null    float64
dtypes: float64(17), object(2)
memory usage: 64.5+ KB

In [ ]:
# simple_imp_med = SimpleImputer(strategy='median')

In [ ]:
# Fill missing cells in the text column with the most frequently occurring value (mode) of that column, using sklearn's SimpleImputer
# This is sklearn's version of the describe().loc['top'] + fillna(most_freq) step

# strategy='most_frequent': each column is filled with the most frequent value of that column
# Unlike strategy='constant' (a general constant like 'MISSING'), here each column has its own fill value, derived from the data at the time of fitting
# No need for fill_value, as the fill value is automatically found by the imputer
# The _freq name indicates that this imputer uses the most frequent value
simple_imp_freq = SimpleImputer(strategy='most_frequent')

# fit: For each column in wdi[cat_cols], find the most frequently occurring value (ignore NaN)
# These values ​​are stored in simple_imp_freq.statistics_
# transform: Replace all NaN with the mode of the corresponding column
# The result is a 2D numpy array of object type stored in imputed_cat
# At this point, wdi is not changed; to write it back, you must assign: wdi[cat_cols] = imputed_cat
imputed_cat = simple_imp_freq.fit_transform(wdi[cat_cols])

In [ ]:
wdi[cat_cols] = imputed_cat

In [ ]:
wdi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country_name                    434 non-null    object
 1   access_to_electricity_pct       434 non-null    float64
 2   atms_per_100000                 434 non-null    float64
 3   compulsory_education_years      434 non-null    float64
 4   health_expenditure_pct_of_gdp   434 non-null    float64
 5   gdp_per_capita_usd              434 non-null    float64
 6   gdp_per_capita_ppp              434 non-null    float64
 7   life_expectancy_female          434 non-null    float64
 8   life_expectancy_male            434 non-null    float64
 9   life_expectancy                 434 non-null    float64
 10  population_density              434 non-null    float64
 11  population                      434 non-null    float64
 12  alcohol_consumption_per_capita  434 non-null    float64
 13  unemployment_rate_female        434 non-null    float64
 14  unemployment_rate_male          434 non-null    float64
 15  unemployment_rate               434 non-null    float64
 16  year                            434 non-null    float64
 17  country_category                434 non-null    object
 18  is_region                       434 non-null    float64
dtypes: float64(17), object(2)
memory usage: 64.5+ KB

In [ ]:
wdi['country_category'].value_counts(dropna=False)

DEVELOPING    376
DEVELOPED      58
Name: country_category, dtype: int64

# Missing Indicator

In [ ]:
wdi = pd.read_pickle('wdi.pkl')

In [ ]:
# Create an imputer that fills in NaN cells with the average of the column, and adds flag columns (0/1) to indicate which cells were originally missing

# strategy='mean': Each NaN cell is replaced with the average of that column (calculated from the data at the time of fitting, ignoring NaN). Only usable for numeric columns
# add_indicator=True: In addition to the filled columns, the imputer appends indicator columns to the right of the result. The value is 1 if the original cell is missing, 0 if there is data
simple_imp_ind = SimpleImputer(strategy='mean', add_indicator=True)

In [ ]:
wdi['compulsory_education_years']

0       9.0
1       9.0
2      10.0
3       6.0
4       9.0
       ...
429    10.0
430    10.0
431    10.0
432     7.0
433     7.0
Name: compulsory_education_years, Length: 434, dtype: float64

In [ ]:
type(wdi['compulsory_education_years'])

pandas.core.series.Series

In [ ]:
wdi[['compulsory_education_years']]

     compulsory_education_years
0                           9.0
1                           9.0
2                          10.0
3                           6.0
4                           9.0
..                          ...
429                        10.0
430                        10.0
431                        10.0
432                         7.0
433                         7.0

[434 rows x 1 columns]

In [ ]:
type(wdi[['compulsory_education_years']])

pandas.core.frame.DataFrame

In [ ]:
# Apply the imputer with the flag column to only one column, compulsory_education_years: fill in NaN with the average, and create an additional column indicating which cells are missing

# wdi[['compulsory_education_years']] has two pairs of [[ ]] so the result is a 1-column DataFrame. This is important: sklearn's fit_transform requires 2D data
# If you write wdi['compulsory_education_years'](Series, 1D), sklearn will report an error: Expected 2D array, got 1D array instead
# simple_imp_ind is the imputer created in the previous step: SimpleImputer(strategy='mean', add_indicator=True)
# fit_transform learns the average of the column (ignore NaN), fills in the missing cells, and then appends the flag column
imputed_ind = simple_imp_ind.fit_transform(wdi[['compulsory_education_years']])

In [ ]:
# imputed_ind is the numpy array with 2 columns from the previous step
# [:20] retrieves the first 20 rows
# Each row has the format [filled value, flag]
imputed_ind[:20]

array([[ 9.        ,  0.        ],
       [ 9.        ,  0.        ],
       [10.        ,  0.        ],
       [ 6.        ,  0.        ],
       [ 9.        ,  0.        ],
       [14.        ,  0.        ],
       [12.        ,  0.        ],
       [10.        ,  0.        ],
       [13.        ,  0.        ],
       [10.        ,  0.        ],
       [12.        ,  0.        ],
       [ 9.        ,  0.        ],
       [ 5.        ,  0.        ],
       [11.        ,  0.        ],
       [ 9.        ,  0.        ],
       [12.        ,  0.        ],
       [ 8.        ,  0.        ],
       [ 6.        ,  0.        ],
       [ 9.70145631,  1.        ],
       [14.        ,  0.        ]])

In [ ]:
imputed_ind.shape

(434, 2)

In [ ]:
# The left side is a 2-column list, the right side is a 2-column array, so pandas assigns the first column of the array to the first column and the second column to the second column

# Compulsory_education_years already exists, so it's overwritten with the data already filled in
# Compulsory_education_years_missing doesn't exist, so pandas creates a new column with the name you set. This is the flag column 0/1

# This command actually fixes wdi. It only runs when the array has exactly 2 columns, meaning this column has NaN during fit
# If the column doesn't have NaN, the array only has 1 column and pandas reports a column mismatch error
wdi[['compulsory_education_years', 'compulsory_education_years_missing']] = imputed_ind

In [ ]:
# Display the first 20 rows of those two columns
# You should see: rows with flags equal to 1 have the same compulsory_education_years value (both are averages), while rows with flags equal to 0 retain the original value
wdi[['compulsory_education_years', 'compulsory_education_years_missing']].head(20)

    compulsory_education_years  compulsory_education_years_missing
0                     9.000000                                 0.0
1                     9.000000                                 0.0
2                    10.000000                                 0.0
3                     6.000000                                 0.0
4                     9.000000                                 0.0
5                    14.000000                                 0.0
6                    12.000000                                 0.0
7                    10.000000                                 0.0
8                    13.000000                                 0.0
9                    10.000000                                 0.0
10                   12.000000                                 0.0
11                    9.000000                                 0.0
12                    5.000000                                 0.0
13                   11.000000                                 0.0
14                    9.000000                                 0.0
15                   12.000000                                 0.0
16                    8.000000                                 0.0
17                    6.000000                                 0.0
18                    9.701456                                 1.0
19                   14.000000                                 0.0